# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 720)

        # ===== 主容器 =====
        self.mainContainer = QtWidgets.QWidget(Form)
        self.mainContainer.setGeometry(QtCore.QRect(0, 0, 480, 720))
        self.mainContainer.setObjectName("mainContainer")

        # 主垂直布局
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.mainContainer)
        self.mainVerticalLayout.setContentsMargins(15, 30, 15, 30)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")

        # ===== 顶部间距 =====
        self.mainVerticalLayout.addStretch()

        # ===== 主标题 =====
        self.mainTitleLabel = TitleLabel(self.mainContainer)
        self.mainTitleLabel.setText("基础信息填写")
        self.mainTitleLabel.setMinimumSize(QtCore.QSize(450, 40))
        self.mainTitleLabel.setMaximumSize(QtCore.QSize(450, 40))
        self.mainVerticalLayout.addWidget(self.mainTitleLabel)
        self.mainVerticalLayout.setAlignment(Qt.AlignCenter)

        # ===== 标题下方间距 =====
        self.mainVerticalLayout.addStretch()

        # ===== 四个输入框水平布局 =====
        self.inputsLayout = QtWidgets.QHBoxLayout()
        self.inputsLayout.addStretch()

        # ------ 第一个输入区块 ------
        self.agentLayout = QtWidgets.QVBoxLayout()
        self.agentLabel = SubtitleLabel(self.mainContainer)
        self.agentLabel.setAlignment(Qt.AlignCenter)
        self.agentLabel.setText("干员代号")
        self.agentLabel.setFixedSize(QtCore.QSize(108, 36))
        self.agentLayout.addWidget(self.agentLabel)
        self.agentComboBox = EditableComboBox(self.mainContainer)
        self.agentComboBox.setFixedSize(QtCore.QSize(108, 36))
        self.agentLayout.addWidget(self.agentComboBox)
        self.inputsLayout.addLayout(self.agentLayout)

        self.inputsLayout.addStretch()

        # ------ 第二个输入区块 ------
        self.skinLayout = QtWidgets.QVBoxLayout()
        self.skinLabel = SubtitleLabel(self.mainContainer)
        self.skinLabel.setAlignment(Qt.AlignCenter)
        self.skinLabel.setText("皮肤名称")
        self.skinLabel.setFixedSize(QtCore.QSize(108, 36))
        self.skinLayout.addWidget(self.skinLabel)
        self.skinComboBox = EditableComboBox(self.mainContainer)
        self.skinComboBox.setFixedSize(QtCore.QSize(108, 36))
        self.skinLayout.addWidget(self.skinComboBox)
        self.inputsLayout.addLayout(self.skinLayout)

        self.inputsLayout.addStretch()

        # ------ 第三个输入区块 ------
        self.brandLayout = QtWidgets.QVBoxLayout()
        self.brandLabel = SubtitleLabel(self.mainContainer)
        self.brandLabel.setAlignment(Qt.AlignCenter)
        self.brandLabel.setText("品牌分类")
        self.brandLabel.setFixedSize(QtCore.QSize(108, 36))
        self.brandLayout.addWidget(self.brandLabel)
        self.brandComboBox = EditableComboBox(self.mainContainer)
        self.brandComboBox.setFixedSize(QtCore.QSize(108, 36))
        self.brandLayout.addWidget(self.brandComboBox)
        self.inputsLayout.addLayout(self.brandLayout)

        self.inputsLayout.addStretch()

        # ------ 第四个输入区块 ------
        self.modelLayout = QtWidgets.QVBoxLayout()
        self.modelLabel = SubtitleLabel(self.mainContainer)
        self.modelLabel.setAlignment(Qt.AlignCenter)
        self.modelLabel.setText("模型分类")
        self.modelLabel.setFixedSize(QtCore.QSize(108, 36))
        self.modelLayout.addWidget(self.modelLabel)
        self.modelComboBox = EditableComboBox(self.mainContainer)
        self.modelComboBox.setFixedSize(QtCore.QSize(108, 36))
        self.modelLayout.addWidget(self.modelComboBox)
        self.inputsLayout.addLayout(self.modelLayout)

        self.inputsLayout.addStretch()
        self.mainVerticalLayout.addLayout(self.inputsLayout)

        # ===== 中间间距 =====
        self.mainVerticalLayout.addStretch()
        self.mainVerticalLayout.addStretch()

        # ===== 设置区 =====
        self.settingsLayout = QtWidgets.QVBoxLayout()

        # 设置标题
        self.settingsTitleLabel = TitleLabel(self.mainContainer)
        self.settingsTitleLabel.setText("基础信息填写")
        self.settingsTitleLabel.setFixedSize(QtCore.QSize(450, 40))
        self.settingsLayout.addWidget(self.settingsTitleLabel)

        self.settingsLayout.addStretch()

        # 配置卡片
        self.configDisplayCard = SimpleCardWidget(self.mainContainer)
        self.configDisplayCard.setFixedSize(QtCore.QSize(450, 160))
        self.settingsLayout.setAlignment(Qt.AlignCenter)
        self.settingsLayout.addWidget(self.configDisplayCard)

        self.mainVerticalLayout.addLayout(self.settingsLayout)

        # ===== 底部设置区 =====
        self.bottomGridLayout = QtWidgets.QGridLayout()

        # 随机种子
        self.seedLabel = SubtitleLabel(self.mainContainer)
        self.seedLabel.setText("填写文件路径")
        self.seedLabel.setFixedSize(QtCore.QSize(225, 50))
        self.bottomGridLayout.addWidget(self.seedLabel, 0, 0)

        self.seedInput = SearchLineEdit(self.mainContainer)
        self.seedInput.setFixedSize(QtCore.QSize(225, 50))
        self.bottomGridLayout.addWidget(self.seedInput, 1, 0)

        # 参数卡片
        self.paramCard = SimpleCardWidget(self.mainContainer)
        self.paramCard.setFixedSize(QtCore.QSize(225, 225))
        self.bottomGridLayout.addWidget(self.paramCard, 2, 0)

        # 按钮组
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.addStretch()

        self.stopTrainingButton = PushButton(self.mainContainer)
        self.stopTrainingButton.setFixedSize(QtCore.QSize(100, 50))

        self.buttonsLayout.addWidget(self.stopTrainingButton)
        self.buttonsLayout.addStretch()

        self.startTrainingButton = PrimaryPushButton(self.mainContainer)
        self.startTrainingButton.setFixedSize(QtCore.QSize(100, 50))

        self.buttonsLayout.addWidget(self.startTrainingButton)
        self.buttonsLayout.addStretch()
        
        self.bottomGridLayout.addLayout(self.buttonsLayout, 1, 1)

        # 状态卡片
        self.statusCard = SimpleCardWidget(self.mainContainer)
        self.statusCard.setFixedSize(QtCore.QSize(225, 225))
        self.bottomGridLayout.addWidget(self.statusCard, 2, 1)

        self.mainVerticalLayout.addLayout(self.bottomGridLayout)

        # ===== 底部间距 =====
        self.mainVerticalLayout.addStretch()

        # 文本设置
        QtCore.QMetaObject.connectSlotsByName(Form)


from qfluentwidgets import EditableComboBox, PushButton, PrimaryPushButton, SearchLineEdit, SimpleCardWidget, TitleLabel, SubtitleLabel


class PreviewWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Form()
        self.ui.setupUi(self)
        self.setWindowTitle("UI Preview")
        self.resize(480, 720)  # 可以调整默认窗口大小


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    from qfluentwidgets import setTheme, Theme

    setTheme(Theme.LIGHT)  # 可选Theme.DARK

    window = PreviewWindow()
    window.show()
    sys.exit(app.exec_())

